import { Language } from "../types";

export const translations = {
  [Language.EN]: {
    appTitle: "CrimeSphere AI",
    appSubtitle: "KSP Investigative Intelligence & Predictive Policing",
    brandFull: "Karnataka State Police - Command Center",
    tagline: "From Crime Data to Actionable Intelligence",
    navDashboard: "Executive Center",
    navVisualization: "Visual Analytics Suite",
    navPrediction: "Hotspot Engine",
    navNetwork: "Network Graph",
    navCyber: "Cyber Intelligence",
    navPilot: "Investigation Co-Pilot",
    navTwin: "Digital Twin Sim",
    navMiner: "Pattern Discovery",

    // Summary Card Labels
    totalCrimes: "Total Crimes Recorded",
    activeCases: "Active Investigations",
    highRiskDistricts: "High Risk Districts",
    cyberCrimeTrends: "Cyber Crime Volume",
    repeatOffenders: "Tracked Repeat Offenders",
    backlogCases: "Investigation Backlog",
    crimeGrowth: "Annual Crime Trend",

    // Filters & Drill down
    drillDownTitle: "Multilevel Crime Drill-Down Dashboard",
    selectState: "State Level View",
    selectDistrict: "Select District",
    selectStation: "Select Police Station",
    allDistricts: "All Districts",
    allStations: "All Stations",
    allCategories: "All Crime Categories",
    allSeverities: "All Severities",
    filterType: "Crime Category",
    filterSeverity: "Severity Level",
    filterStatus: "Case Status",

    // Predictor Page
    predictorTitle: "Predictive Hotspot Hot-Grid & Resource Planning",
    predictedHotspots: "AI Predictive Crime Hotspots (30-Day Window)",
    riskAnalysis: "Explainable AI (XAI) SHAP/LIME Feature Contribution",
    deployRecommended: "Recommended Patrol Strategy & Resource Allocation",
    confidence: "Confidence Score",
    forecastingOutput: "Spatio-Temporal Forecast Output",

    // Network Graph Page
    networkTitle: "Criminal Relationship Network Graph (GNN Community Detection)",
    networkSub: "Trace connections between suspects, IP addresses, bank accounts, and locations. Highlights hidden cyber fraud syndicates.",
    nodeType: "Node Class",
    pagerank: "PageRank Centrality",
    syndicates: "Uncovered Syndicate Clusters",

    // Cyber Intelligence Page
    cyberTitle: "Cyber Fraud & Money Mule Detection Engine",
    cyberSub: "Anomaly scores generated by isolation forests & graph neural networks mapping mule accounts and burner devices.",
    anomalyScore: "Anomaly Risk Rating",
    flaggedMules: "Mule Accounts Flagged",
    reuseRate: "IP/Device Reuse Rate",

    // Co-Pilot Page
    copilotTitle: "Intelligence Co-Pilot (Text-to-SQL & Document RAG)",
    copilotSub: "Type in English, Kannada, or Hindi to generate complex queries, summaries, analytical charts, or legal briefs.",
    copilotPlaceholder: "Ask CrimeSphere: 'Show cyber fraud patterns in Bengaluru East' or type in Kannada...",
    copilotDisclaimer: "Generates secure SQL, queries regional DB clusters, and compiles visual intelligence reports.",

    // Digital Twin Page
    twinTitle: "Crime Digital Twin & Policework Sandbox",
    twinSub: "Simulate operational adjustments, awareness level increases, or weather events inside a virtual model of Karnataka's police network.",
    runSimulation: "Execute Virtual Sandbox Simulation",
    simSuccess: "Simulation finished. Metrics successfully forecasted by Graph Temporal Models.",

    // Pattern Miner Page
    minerTitle: "Crime Pattern FP-Growth Co-Occurrence Engine",
    minerSub: "Mines implicit rules and correlations between geography, timing, target demographics, and modus operandi.",

    // Alerts System
    alertsCenter: "State Intelligence Alerts",
    markAllRead: "Mark all as read",

    // General Words
    severityHigh: "High",
    severityMod: "Moderate",
    severityLow: "Low",
    statusOpen: "Open",
    statusInves: "Under Investigation",
    statusSolved: "Solved",
    statusClosed: "Closed"
  },

  [Language.KN]: {
    appTitle: "ಅಪರಾಧಸ್ಪಿಯರ್ AI (CrimeSphere AI)",
    appSubtitle: "ಕೆಎಸ್ಪಿ ತನಿಖಾ ಬುದ್ಧಿಮತ್ತೆ ಮತ್ತು ಮುನ್ಸೂಚಕ ತರಬೇತಿ",
    brandFull: "ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ - ಕಮಾಂಡ್ ಸೆಂಟರ್",
    tagline: "ಅಪರಾಧದ ದತ್ತಾಂಶದಿಂದ ಕ್ರಿಯಾಶೀಲ ಬುದ್ಧಿಮತ್ತೆಯವರೆಗೆ",
    navDashboard: "ಕಾರ್ಯನಿರ್ವಾಹಕ ಕೇಂದ್ರ",
    navVisualization: "ದೃಶ್ಯ ವಿಶ್ಲೇಷಣೆ ಸೂಟ್",
    navPrediction: "ಹಾಟ್‌ಸ್ಪಾಟ್ ಮುನ್ಸೂಚನೆ",
    navNetwork: "ಸಂಬಂಧಗಳ ಆಕೃತಿ",
    navCyber: "ಸೈಬರ್ ಗುಪ್ತಚರ",
    navPilot: "ತನಿಖಾ ಸಹ-ಪೈಲಟ್",
    navTwin: "ಡಿಜಿಟಲ್ ಅವಳಿ ಸಿಮ್ಯುಲೇಶನ್",
    navMiner: "ನಮೂನೆಗಳ ಶೋಧನೆ",

    // Summary Card Labels
    totalCrimes: "ಒಟ್ಟು ದಾಖಲಾದ ಅಪರಾಧಗಳು",
    activeCases: "ಸಕ್ರಿಯ ತನಿಖೆಗಳು",
    highRiskDistricts: "ಹೆಚ್ಚು ಅಪಾಯದ ಜಿಲ್ಲೆಗಳು",
    cyberCrimeTrends: "ಸೈಬರ್ ಅಪರಾಧದ ಪ್ರಮಾಣ",
    repeatOffenders: "ಗಮನಿಸಿದ ಅಪರಾಧಿಗಳು",
    backlogCases: "ಬಾಕಿ ಇರುವ ತನಿಖೆಗಳು",
    crimeGrowth: "ವಾರ್ಷಿಕ ಅಪರಾಧ ಪ್ರವೃತ್ತಿ",

    // Filters & Drill down
    drillDownTitle: "ಬಹುಮಟ್ಟದ ಅಪರಾಧ ಪರಿಶೋಧನಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    selectState: "ರಾಜ್ಯ ಮಟ್ಟದ ನೋಟ",
    selectDistrict: "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    selectStation: "ಪೊಲೀಸ್ ಠಾಣೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    allDistricts: "ಎಲ್ಲಾ ಜಿಲ್ಲೆಗಳು",
    allStations: "ಎಲ್ಲಾ ಠಾಣೆಗಳು",
    allCategories: "ಎಲ್ಲಾ ಅಪರಾಧ ವರ್ಗಗಳು",
    allSeverities: "ಎಲ್ಲಾ ಹಂತಗಳು",
    filterType: "ಅಪರಾಧ ವರ್ಗ",
    filterSeverity: "ಗಂಭೀರತೆಯ ಹಂತ",
    filterStatus: "ಪ್ರಕರಣದ ಸ್ಥಿತಿ",

    // Predictor Page
    predictorTitle: "ಮುನ್ಸೂಚಕ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಮತ್ತು ಸಂಪನ್ಮೂಲ ಯೋಜನೆ",
    predictedHotspots: "AI ಮುನ್ಸೂಚಕ ಅಪರಾಧ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು (30 ದಿನಗಳ ಕಾಲಮಿತಿ)",
    riskAnalysis: "ವಿವರಣಾತ್ಮಕ AI (XAI) SHAP/LIME ವೈಶಿಷ್ಟ್ಯಗಳ ಕೊಡುಗೆ",
    deployRecommended: "ಶಿಫಾರಸು ಮಾಡಿದ ಗಸ್ತು ತಂತ್ರ ಮತ್ತು ಸಂಪನ್ಮೂಲ ನಿಯೋಜನೆ",
    confidence: "ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಸ್ಕೋರ್",
    forecastingOutput: "ಸ್ಥಳೀಯ-ತಾತ್ಕಾಲಿಕ ಮುನ್ಸೂಚನೆಯ ಫಲಿತಾಂಶ",

    // Network Graph Page
    networkTitle: "ಅಪರಾಧಿಗಳ ಸಂಬಂಧ ಜಾಲ ಆಕೃತಿ (GNN ಸಮುದಾಯ ಪತ್ತೆ)",
    networkSub: "ಶಂಕಿತರು, ಐಪಿ ವಿಳಾಸಗಳು, ಬ್ಯಾಂಕ್ ಖಾತೆಗಳು ಮತ್ತು ಸ್ಥಳಗಳ ನಡುವಿನ ಸಂಬಂಧ ಪತ್ತೆ ಮಾಡಿ. ಗುಪ್ತ ಸೈಬರ್ ಗ್ಯಾಂಗ್‌ಗಳನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತದೆ.",
    nodeType: "ನೋಡ್ ವರ್ಗ",
    pagerank: "ಪೇಜ್‌ರ‍್ಯಾಂಕ್ ಪ್ರಮುಖತೆ",
    syndicates: "ಪತ್ತೆಯಾದ ಅಪರಾಧಿ ತಂಡಗಳು",

    // Cyber Intelligence Page
    cyberTitle: "ಸೈಬರ್ ವಂಚನೆ ಮತ್ತು ಮನಿ ಮ್ಯೂಲ್ ಪತ್ತೆ ಎಂಜಿನ್",
    cyberSub: "ಐಸೊಲೇಶನ್ ಫಾರೆಸ್ಟ್ ಮತ್ತು ಗ್ರಾಫ್ ಜಾಲಗಳು ಮ್ಯೂಲ್ ಖಾತೆಗಳು ಹಾಗೂ ನಕಲಿ ಫೋನ್‌ಗಳನ್ನು ಗುರುತಿಸಿ ನೀಡಿದ ಸ್ಕೋರ್.",
    anomalyScore: "ಅಪಸಾಮಾನ್ಯ ಅಪಾಯದ ರೇಟಿಂಗ್",
    flaggedMules: "ಫ್ಲ್ಯಾಗ್ ಮಾಡಲಾದ ಮ್ಯೂಲ್ ಖಾತೆಗಳು",
    reuseRate: "ಐಪಿ/ಸಾಧನ ಮರುಬಳಕೆ ದರ",

    // Co-Pilot Page
    copilotTitle: "ಬುದ್ಧಿಮತ್ತೆ ಸಹ-ಪೈಲಟ್ (ಪಠ್ಯದಿಂದ SQL ಮತ್ತು ಡಾಕ್ಯುಮೆಂಟ್ RAG)",
    copilotSub: "ಸಂಕೀರ್ಣ ಪ್ರಶ್ನೆಗಳು, ಸಾರಾಂಶಗಳು, ಅಥವಾ ಚಾರ್ಟ್‌ಗಳನ್ನು ರಚಿಸಲು ಇಂಗ್ಲಿಷ್, ಕನ್ನಡ ಅಥವಾ ಹಿಂದಿಯಲ್ಲಿ ಕೇಳಿ.",
    copilotPlaceholder: "ಅಪರಾಧಸ್ಪಿಯರ್ ಗೆ ಕೇಳಿ: 'ಬೆಂಗಳೂರು ಪೂರ್ವದಲ್ಲಿ ಸೈಬರ್ ವಂಚನೆ ನಮೂನೆಗಳನ್ನು ತೋರಿಸು'...",
    copilotDisclaimer: "ಸುರಕ್ಷಿತ SQL ಅನ್ನು ರಚಿಸುತ್ತದೆ, ಪ್ರಾದೇಶಿಕ ಡೇಟಾಬೇಸ್‌ಗಳನ್ನು ಪ್ರಶ್ನಿಸುತ್ತದೆ ಮತ್ತು ದೃಶ್ಯ ಗುಪ್ತಚರ ವರದಿಗಳನ್ನು ಸಂಕಲಿಸುತ್ತದೆ.",

    // Digital Twin Page
    twinTitle: "ಡಿಜಿಟಲ್ ಅವಳಿ ಮತ್ತು ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಸಿಮ್ಯುಲೇಶನ್",
    twinSub: "ಕರ್ನಾಟಕದ ಪೊಲೀಸ್ ಜಾಲದ ಸಿಮ್ಯುಲೇಶನ್‌ನಲ್ಲಿ ಕಾರ್ಯಾಚರಣೆ ಬದಲಾವಣೆಗಳು ಅಥವಾ ಜಾಗೃತಿ ಅಭಿಯಾನಗಳ ಪರಿಣಾಮ ತಪಾಸಣೆ ಮಾಡಿ.",
    runSimulation: "ವರ್ಚುವಲ್ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಸಿಮ್ಯುಲೇಶನ್ ಚಾಲನೆ ಮಾಡಿ",
    simSuccess: "ಸಿಮ್ಯುಲೇಶನ್ ಪೂರ್ಣಗೊಂಡಿದೆ. ಗ್ರಾಫ್ ಟೆಂಪರಲ್ ಮಾದರಿಗಳಿಂದ ಯಶಸ್ವಿಯಾಗಿ ಅಂದಾಜು ಮಾಡಲಾಗಿದೆ.",

    // Pattern Miner Page
    minerTitle: "ಅಪರಾಧ ನಮೂನೆ ಕರಾರಿನ ವಿಶ್ಲೇಷಣೆ (FP-Growth Engine)",
    minerSub: "ಭೌಗೋಳಿಕತೆ, ಸಮಯ ಮತ್ತು ಅಪರಾಧದ ವಿಧಾನಗಳ ನಡುವಿನ ಗುಪ್ತ ಸಂಬಂಧಗಳನ್ನು ಕಲಿಯಿರಿ.",

    // Alerts System
    alertsCenter: "ರಾಜ್ಯ ಗುಪ್ತಚರ ಎಚ್ಚರಿಕೆಗಳು",
    markAllRead: "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸು",

    // General Words
    severityHigh: "ಹೆಚ್ಚು ತೀವ್ರ",
    severityMod: "ಮಧ್ಯಮ",
    severityLow: "ಕಡಿಮೆ",
    statusOpen: "ತೆರೆದಿದೆ",
    statusInves: "ತನಿಖೆಯಲ್ಲಿದೆ",
    statusSolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    statusClosed: "ಮುಚ್ಚಲಾಗಿದೆ"
  },

  [Language.HI]: {
    appTitle: "क्राइमस्फीयर AI (CrimeSphere AI)",
    appSubtitle: "केएसपी खुफिया जांच और पूर्वानुमानित पुलिसिंग",
    brandFull: "कर्नाटक राज्य पुलिस - कमांड सेंटर",
    tagline: "अपराध डेटा से कार्रवाई योग्य खुफिया जानकारी तक",
    navDashboard: "कमांड सेंटर",
    navVisualization: "दृश्य विश्लेषण सूट",
    navPrediction: "हॉटस्पॉट अनुमान",
    navNetwork: "संबंध आरेख",
    navCyber: "साइबर इंटेलिजेंस",
    navPilot: "जांच सह-पायलट",
    navTwin: "डिजिटल ट्विन सिमुलेशन",
    navMiner: "पैटर्न खोज",

    // Summary Card Labels
    totalCrimes: "कुल दर्ज अपराध",
    activeCases: "सक्रिय जांच",
    highRiskDistricts: "उच्च जोखिम वाले जिले",
    cyberCrimeTrends: "साइबर अपराध मात्रा",
    repeatOffenders: "ट्रैक किए गए अपराधी",
    backlogCases: "लंबित मामले",
    crimeGrowth: "वार्षिक अपराध प्रवृत्ति",

    // Filters & Drill down
    drillDownTitle: "बहु-स्तरीय अपराध अनुसंधान डैशबोर्ड",
    selectState: "राज्य स्तरीय दृश्य",
    selectDistrict: "जिले का चयन करें",
    selectStation: "थाने का चयन करें",
    allDistricts: "सभी जिले",
    allStations: "सभी थाने",
    allCategories: "सभी अपराध श्रेणियां",
    allSeverities: "सभी गंभीरता स्तर",
    filterType: "अपराध श्रेणी",
    filterSeverity: "गंभीरता स्तर",
    filterStatus: "मामले की स्थिति",

    // Predictor Page
    predictorTitle: "पूर्वानुमान हॉटस्पॉट और संसाधन योजना",
    predictedHotspots: "AI पूर्वानुमानित अपराध हॉटस्पॉट (30-दिन की अवधि)",
    riskAnalysis: "व्याख्यात्मक AI (XAI) SHAP/LIME योगदान",
    deployRecommended: "अनुशंसित गश्ती रणनीति और संसाधन आवंटन",
    confidence: "आत्मविश्वास स्कोर",
    forecastingOutput: "स्थानिक-कालिक पूर्वानुमान परिणाम",

    // Network Graph Page
    networkTitle: "अपराधी संबंध नेटवर्क ग्राफ (GNN समुदाय पहचान)",
    networkSub: "संदिग्धों, आईपी पते, बैंक खातों और स्थानों के संबंध ट्रैक करें। छिपे साइबर सिंडिकेट को उजागर करता है।",
    nodeType: "नोड श्रेणी",
    pagerank: "पेजरैंक प्रमुखता",
    syndicates: "उजागर सिंडिकेट समूह",

    // Cyber Intelligence Page
    cyberTitle: "साइबर धोखाधड़ी और मनी म्यूल डिटेक्शन इंजन",
    cyberSub: "आइसोलेशन फॉरेस्ट और ग्राफ तंत्र द्वारा चिन्हित संदिग्ध खाते और बर्नर उपकरण स्कोर।",
    anomalyScore: "असामान्य जोखिम रेटिंग",
    flaggedMules: "चिन्हित संदिग्ध खाते",
    reuseRate: "आईपी/साधना पुन: उपयोग दर",

    // Co-Pilot Page
    copilotTitle: "इंटेलिजेंस सह-पायलट (टेक्स्ट-टू-SQL और दस्तावेज़ RAG)",
    copilotSub: "जटिल प्रश्न पूछें, सारांश बनाएं या चार्ट बनाने के लिए अंग्रेजी, कन्नड़ या हिंदी में लिखें।",
    copilotPlaceholder: "क्राइमस्फीयर से पूछें: 'बेंगलुरु पूर्व में साइबर धोखाधड़ी पैटर्न दिखाएं'...",
    copilotDisclaimer: "सुरक्षित SQL जेनरेट करता है, क्षेत्रीय डेटाबेस का विश्लेषण करता है और विज़ुअल रिपोर्ट्स बनाता है।",

    // Digital Twin Page
    twinTitle: "डिजिटल ट्विन और सैंडबॉक्स सिमुलेशन",
    twinSub: "कर्नाटक पुलिस नेटवर्क के डिजिटल मॉडल में परिचालन परिवर्तनों या जागरूकता अभियानों के प्रभावों को परखें।",
    runSimulation: "वर्चुअल सैंडबॉक्स सिमुलेशन चलाएं",
    simSuccess: "सिमुलेशन समाप्त। ग्राफ टेम्पोरल मॉडल द्वारा सफलतापूर्वक अनुमानित परिणाम।",

    // Pattern Miner Page
    minerTitle: "अपराध पैटर्न मिलान (FP-Growth Engine)",
    minerSub: "भूगोल, समय और अपराध के तरीकों के बीच अंतर्निहित संवर्धनाओं को बाहर निकालें।",

    // Alerts System
    alertsCenter: "राज्य खुफिया अलर्ट",
    markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",

    // General Words
    severityHigh: "उच्च गंभीर",
    severityMod: "मध्यम",
    severityLow: "कम",
    statusOpen: "खुला है",
    statusInves: "जांच जारी",
    statusSolved: "हल किया गया",
    statusClosed: "बंद है"
  }
};
